import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';

type Theme = 'dark' | 'light';
type Language = 'ru' | 'en' | 'kk';

const DICTIONARY: Record<Language, Record<string, string>> = {
  ru: {
    'brand.name': 'Cognify',
    'layout.logout': 'Выйти',
    'layout.theme': 'Тема',
    'layout.language': 'Язык',
    'layout.dark': 'Темная',
    'layout.light': 'Светлая',
    'nav.teacher.dashboard': 'Обзор',
    'nav.teacher.courses': 'Мои курсы',
    'nav.teacher.create': 'Создать курс',
    'nav.teacher.students': 'Студенты',
    'nav.student.dashboard': 'Мое обучение',
    'nav.student.catalog': 'Каталог',
    'nav.student.admin': 'Аналитика',
    'auth.title': 'Cognify',
    'auth.login.subtitle': 'Войдите, чтобы продолжить обучение',
    'auth.register.subtitle': 'Создайте аккаунт для обучения',
    'auth.login': 'Войти',
    'auth.register': 'Регистрация',
    'auth.name': 'Имя',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.student': 'Студент',
    'auth.teacher': 'Преподаватель',
    'teacher.welcome': 'С возвращением, {name}',
    'teacher.workspace': 'Ваше рабочее пространство готово',
    'teacher.createCourse': 'Создать курс',
    'teacher.totalStudents': 'Всего студентов',
    'teacher.activeCourses': 'Активные курсы',
    'teacher.enrollments': 'Записей',
    'teacher.aiCourses': 'AI курсы',
    'teacher.avgScore': 'Средняя оценка',
    'teacher.completion': 'Завершено',
    'teacher.atRisk': 'В группе риска',
    'teacher.weakTopics': 'Слабые темы',
    'course.lessons': 'Уроки',
    'course.modules': 'Модули',
    'course.students': 'Студентов',
    'course.progress': 'Прогресс',
    'course.start': 'Начать',
    'course.continue': 'Продолжить',
    'teacher.riskGroup': 'Группа риска (<50)',
    'teacher.needsAttention': 'Требует внимания',
    'teacher.courseHealth': 'Здоровье курса',
    'teacher.recentCourses': 'Недавние курсы',
    'teacher.noCourses': 'Нет курсов.',
    'teacher.viewAllCourses': 'Просмотреть все курсы',
    'teacher.studentsAtRisk': 'Студенты в группе риска',
    'teacher.noRiskStudents': 'Нет студентов в группе риска.',
    'teacher.openGrading': 'Открыть оценивание',
    'teacher.weakTopicsAnalytics': 'Аналитика слабых тем появится после попыток студентов.',
    'teacher.flags': 'флаги',
    'teacher.automationSnapshot': 'Снимок автоматизации',
    'teacher.automationDesc': 'Конструктор AI, оценка рисков, оценивание, адаптивные тесты, сертификаты и персонализированное руководство студентами теперь подключены.',
    'teacher.completionRate': 'Процент завершения',
    'teacher.averageScore': 'Средняя оценка',
    'student.catalog.title': 'Explore Knowledge',
    'student.catalog.subtitle': 'Personalized AI-powered learning paths just for you.',
    'student.catalog.searchPlaceholder': 'Search courses...',
    'student.catalog.trendingTitle': 'Trending Topics',
    'student.catalog.clearFilter': 'Clear filter',
    'student.catalog.resourcesTitle': 'Related Resources',
    'student.catalog.resource.precision.title': 'Precision Agriculture Basics',
    'student.catalog.resource.precision.desc': 'Data-driven farming, crop monitoring, and precision input planning.',
    'student.catalog.resource.drone.title': 'Drone Mapping for Agriculture',
    'student.catalog.resource.drone.desc': 'Drone surveys, mapping routes, imagery capture, and field inspection workflows.',
    'student.catalog.resource.soil.title': 'Agronomy and Soil Management',
    'student.catalog.resource.soil.desc': 'Soil fertility, irrigation, crop rotation, and sustainable field decisions.',
    'student.catalog.noCourses': 'No courses available at the moment.',
    'student.catalog.enroll': 'Enroll',
    'student.catalog.enrolling': 'Enrolling...',
    'student.catalog.enrollSuccess': 'You have successfully enrolled in this course.',
    'student.catalog.enrollError': 'Enrollment failed. Please try again.',
    'student.catalog.favoriteAdded': 'Course added to favorites.',
    'student.catalog.favoriteRemoved': 'Course removed from favorites.',
    'student.catalog.defaultCourseDescription': 'Dive into this curated curriculum and master new horizons with Cognify AI.',
    'teacher.courses.descriptionFallback': 'Use this space to describe what students will learn in this course.',
    'student.dashboard.heroTitle': 'Welcome back, {name}! Ready to continue your AI journey?',
    'student.dashboard.heroSubtitle.courses': 'Your personalized learning paths are ready. Select a course to keep making progress.',
    'student.dashboard.heroSubtitle.empty': 'You have not enrolled in any courses yet. Check the Course Catalog to begin your learning.',
    'student.dashboard.browseCatalog': 'Browse Catalog',
    'student.dashboard.portfolioTitle': 'Your Learning Portfolio',
    'student.dashboard.loadingDashboard': 'Loading your dashboard...',
    'student.dashboard.noCourses': 'You are not enrolled in any courses right now.',
    'student.dashboard.recommendationsTitle': 'Your Next Actions',
    'student.dashboard.recommendedCoursesTitle': 'Recommended Next Courses',
    'student.dashboard.recommendationsEmpty': 'Complete a lesson or quiz to unlock a personalized action plan.',
    'student.dashboard.recommendedCoursesEmpty': 'New course suggestions will appear here as your learning profile grows.',
    'student.dashboard.focusAreasTitle': 'Focus Areas',
    'student.dashboard.focusAreasEmpty': 'Your weak-topic analysis will appear here after quiz attempts.',
    'student.dashboard.resumeLearning': 'Resume Learning',
    'teacher.courses.title': 'My Courses',
    'teacher.courses.headerDesc': 'Manage your teaching portfolio and create courses with confidence.',
    'teacher.courses.searchPlaceholder': 'Search course titles or descriptions...',
    'teacher.courses.filterAll': 'All Courses',
    'teacher.courses.filterAI': 'AI Courses',
    'teacher.courses.filterManual': 'Manual Courses',
    'teacher.courses.noMatches': 'No courses match the current filters.',
    'teacher.courses.sharedTitle': 'Community Courses',
    'teacher.courses.sharedSubtitle': 'Courses created or added beyond your personal teaching catalog.',
    'teacher.courses.aiGenerated': 'AI Generated',
    'teacher.courses.manual': 'Manual',
    'teacher.courses.students': '{count} students',
    'teacher.courses.openCourse': 'Open Course',
    'teacher.courses.editCourse': 'Edit Course',
    'landing.nav.features': 'Возможности',
    'landing.nav.solutions': 'Решения',
    'landing.nav.signin': 'Войти',
    'landing.hero.badge': '🚀 Cognify 2.0 запущен',
    'landing.hero.title': 'ОС нового поколения<br/>для обучения.',
    'landing.hero.subtitle': 'Вовлекайте студентов с помощью адаптивного AI-обучения, RPG-режимов и продвинутой аналитики.',
    'landing.hero.cta.start': 'Начать бесплатно',
    'landing.hero.cta.explore': 'Платформа',
    'landing.preview.shield': 'Проверено ИИ',
    'landing.preview.score': 'Балл: 98% 🌟',
    'landing.preview.level': 'Новый уровень!',
    'landing.preview.levelSub': 'Вы достигли 12 уровня',
    'landing.features.title': 'Создано для современных учеников',
    'landing.features.subtitle': 'Всё необходимое для выдающегося образовательного опыта.',
    'landing.features.ai.title': 'Создание с помощью ИИ',
    'landing.features.ai.desc': 'Генерируйте целые курсы, квизы и пути обучения за секунды.',
    'landing.features.rpg.title': 'Геймификация RPG',
    'landing.features.rpg.desc': 'Студенты исследуют острова, получают опыт и открывают сундуки.',
    'landing.features.analytics.title': 'Аналитика в Реал-Тайме',
    'landing.features.analytics.desc': 'Мгновенно находите отстающих с помощью алгоритмов оценки рисков и кастомных PDF-отчетов.',
    'common.loading': 'Загрузка...',
    'nav.aiLibrary': 'AI Библиотека',
    'ai.library.title': 'AI Библиотека',
    'ai.library.subtitle': 'Исследуйте образовательные ресурсы и ИИ-инструменты',
    'ai.library.searchLabel': 'Поисковый запрос или текст',
    'ai.library.searchPlaceholder': 'Введите тему, слово или текст...',
    'ai.library.mode': 'Режим',
    'ai.library.mode.search': 'Поиск по библиотеке',
    'ai.library.mode.translate': 'Перевод текста',
    'ai.library.mode.summarize': 'Суммаризация',
    'ai.library.targetLang': 'Язык перевода',
    'ai.library.action.search': 'Найти',
    'ai.library.action.processing': 'Обработка...',
    'ai.library.results.translation': 'Перевод',
    'ai.library.results.summary': 'Сводка',
    'ai.library.results.items': 'Объекты библиотеки',
    'ai.library.results.related': 'Связанные ресурсы',
    'ai.library.empty': 'Введите запрос для поиска в библиотеке',
    'ai.library.copy': 'Копировать',
    'ai.library.copied': 'Скопировано в буфер',
    'student.catalog.viewMore': 'Смотреть курс',
    'student.catalog.communityBadge': 'Сообщество',
    'teacher.students.gradingTitle': 'Студенты и Оценки',
    'teacher.students.selectCourse': 'Выберите курс',
    'teacher.students.table.student': 'Студент',
    'teacher.students.table.average': 'Средний балл',
    'teacher.students.noStudents': 'Студентов пока нет',
    'common.xp': 'XP: {xp}',
    'common.streakDays': '{days} дн. подряд',
    'common.level': '{level} уровень',
  },
  en: {
    'brand.name': 'Cognify',
    'layout.logout': 'Logout',
    'layout.theme': 'Theme',
    'layout.language': 'Language',
    'layout.dark': 'Dark',
    'layout.light': 'Light',
    'nav.teacher.dashboard': 'Overview',
    'nav.teacher.courses': 'My Courses',
    'nav.teacher.create': 'Create Course',
    'nav.teacher.students': 'Students',
    'nav.student.dashboard': 'My Learning',
    'nav.student.catalog': 'Catalog',
    'nav.student.admin': 'Analytics',
    'auth.title': 'Cognify',
    'auth.login.subtitle': 'Sign in to continue learning',
    'auth.register.subtitle': 'Create an account to start learning',
    'auth.login': 'Sign In',
    'auth.register': 'Create Account',
    'auth.name': 'Full Name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.student': 'Student',
    'auth.teacher': 'Teacher',
    'teacher.welcome': 'Welcome back, {name}',
    'teacher.workspace': 'Your teaching workspace is ready',
    'teacher.createCourse': 'Create Course',
    'teacher.totalStudents': 'Total Students',
    'teacher.activeCourses': 'Active Courses',
    'teacher.enrollments': 'Enrollments',
    'teacher.aiCourses': 'AI Courses',
    'teacher.avgScore': 'Avg Score',
    'teacher.completion': 'Completion',
    'teacher.atRisk': 'At Risk',
    'teacher.weakTopics': 'Weak Topics',
    'course.lessons': 'Lessons',
    'course.modules': 'Modules',
    'course.students': 'Students',
    'course.progress': 'Progress',
    'course.start': 'Start',
    'course.continue': 'Continue',
    'teacher.riskGroup': 'Risk Group (<50)',
    'teacher.needsAttention': 'Needs attention',
    'teacher.courseHealth': 'Course Health',
    'teacher.recentCourses': 'Recent Courses',
    'teacher.noCourses': 'No courses yet.',
    'teacher.viewAllCourses': 'View all courses',
    'teacher.studentsAtRisk': 'Students at Risk',
    'teacher.noRiskStudents': 'No risk students yet.',
    'teacher.openGrading': 'Open grading',
    'teacher.weakTopicsAnalytics': 'Weak-topic analytics will appear after student quiz attempts.',
    'teacher.flags': 'flags',
    'teacher.automationSnapshot': 'Automation Snapshot',
    'teacher.automationDesc': 'AI builder, risk scoring, grading, adaptive tests, certificates, and personalized student guidance are now connected.',
    'teacher.completionRate': 'Completion rate',
    'teacher.averageScore': 'Average score',
    'student.catalog.title': 'Explore Knowledge',
    'student.catalog.subtitle': 'Personalized AI-powered learning paths just for you.',
    'student.catalog.searchPlaceholder': 'Search courses...',
    'student.catalog.trendingTitle': 'Trending Topics',
    'student.catalog.clearFilter': 'Clear filter',
    'student.catalog.resourcesTitle': 'Related Resources',
    'student.catalog.resource.precision.title': 'Precision Agriculture Basics',
    'student.catalog.resource.precision.desc': 'Data-driven farming, crop monitoring, and precision input planning.',
    'student.catalog.resource.drone.title': 'Drone Mapping for Agriculture',
    'student.catalog.resource.drone.desc': 'Drone surveys, mapping routes, imagery capture, and field inspection workflows.',
    'student.catalog.resource.soil.title': 'Agronomy and Soil Management',
    'student.catalog.resource.soil.desc': 'Soil fertility, irrigation, crop rotation, and sustainable field decisions.',
    'student.catalog.noCourses': 'No courses available at the moment.',
    'student.catalog.completed': 'Completed',
    'student.catalog.progress': 'Progress',
    'student.dashboard.aiTutorStatus': 'AI Tutor Active',
    'student.dashboard.heroTitle': 'Welcome back, {name}! Ready to continue your AI journey?',
    'student.dashboard.heroSubtitle.courses': 'Your personalized learning paths are ready. Select a course to keep making progress.',
    'student.dashboard.heroSubtitle.empty': 'You have not enrolled in any courses yet. Check the Course Catalog to begin your learning.',
    'student.dashboard.browseCatalog': 'Browse Catalog',
    'student.dashboard.portfolioTitle': 'Your Learning Portfolio',
    'student.dashboard.loadingDashboard': 'Loading your dashboard...',
    'student.dashboard.noCourses': 'You are not enrolled in any courses right now.',
    'student.dashboard.recommendationsTitle': 'Your Next Actions',
    'student.dashboard.recommendedCoursesTitle': 'Recommended Next Courses',
    'student.dashboard.recommendationsEmpty': 'Complete a lesson or quiz to unlock a personalized action plan.',
    'student.dashboard.recommendedCoursesEmpty': 'New course suggestions will appear here as your learning profile grows.',
    'student.dashboard.focusAreasTitle': 'Focus Areas',
    'student.dashboard.focusAreasEmpty': 'Your weak-topic analysis will appear here after quiz attempts.',
    'student.dashboard.resumeLearning': 'Resume Learning',
    'teacher.courses.title': 'My Courses',
    'teacher.courses.headerDesc': 'Manage your teaching portfolio and create courses with confidence.',
    'teacher.courses.searchPlaceholder': 'Search course titles or descriptions...',
    'teacher.courses.filterAll': 'All Courses',
    'teacher.courses.filterAI': 'AI Courses',
    'teacher.courses.filterManual': 'Manual Courses',
    'teacher.courses.noMatches': 'No courses match the current filters.',
    'teacher.courses.sharedTitle': 'Community Courses',
    'teacher.courses.sharedSubtitle': 'Courses created or added beyond your personal teaching catalog.',
    'teacher.courses.aiGenerated': 'AI Generated',
    'teacher.courses.manual': 'Manual',
    'teacher.courses.students': '{count} students',
    'teacher.courses.openCourse': 'Open Course',
    'teacher.courses.editCourse': 'Edit Course',
    'student.catalog.enroll': 'Enroll',
    'student.catalog.enrolling': 'Enrolling...',
    'student.catalog.enrollSuccess': 'You have successfully enrolled in this course.',
    'student.catalog.enrollError': 'Enrollment failed. Please try again.',
    'student.catalog.favoriteAdded': 'Course added to favorites.',
    'student.catalog.favoriteRemoved': 'Course removed from favorites.',
    'student.catalog.defaultCourseDescription': 'Dive into this curated curriculum and master new horizons with Cognify AI.',
    'landing.nav.features': 'Features',
    'landing.nav.solutions': 'Solutions',
    'landing.nav.signin': 'Sign In',
    'landing.hero.badge': '🚀 Cognify 2.0 is now live',
    'landing.hero.title': 'The Operating System<br/>for Next-Gen Learning.',
    'landing.hero.subtitle': 'Empower your students with AI-driven adaptive learning, immersive RPG game modes, and deep enterprise analytics.',
    'landing.hero.cta.start': 'Get Started Free',
    'landing.hero.cta.explore': 'Explore Platform',
    'landing.preview.shield': 'AI Graded',
    'landing.preview.score': 'Score: 98% 🌟',
    'landing.preview.level': 'Level Up!',
    'landing.preview.levelSub': 'You reached Level 12',
    'landing.features.title': 'Built for the Modern Learner',
    'landing.features.subtitle': 'Everything you need to deliver world-class educational experiences.',
    'landing.features.ai.title': 'AI-Powered Creation',
    'landing.features.ai.desc': 'Generate entire courses, quizzes, and adaptive learning paths in seconds.',
    'landing.features.rpg.title': 'RPG Gamification',
    'landing.features.rpg.desc': 'Turn curriculum into a 2D map. Students explore islands and earn XP.',
    'landing.features.analytics.title': 'Real-time Analytics',
    'landing.features.analytics.desc': 'Instantly spot struggling students with risk scoring and PDF reports.',
    'common.loading': 'Loading...',
    'nav.aiLibrary': 'AI Library',
    'ai.library.title': 'AI Library',
    'ai.library.subtitle': 'Explore educational resources and AI-powered tools',
    'ai.library.searchLabel': 'Search Query or Text',
    'ai.library.searchPlaceholder': 'Enter topic, keyword, or text...',
    'ai.library.mode': 'Mode',
    'ai.library.mode.search': 'Search Library',
    'ai.library.mode.translate': 'Translate Text',
    'ai.library.mode.summarize': 'Summarize Text',
    'ai.library.targetLang': 'Target Language',
    'ai.library.action.search': 'Search',
    'ai.library.action.processing': 'Processing...',
    'ai.library.results.translation': 'Translation',
    'ai.library.results.summary': 'Summary',
    'ai.library.results.items': 'Library Items',
    'ai.library.results.related': 'Related Resources',
    'ai.library.empty': 'Enter a query to explore the AI Library',
    'ai.library.copy': 'Copy',
    'ai.library.copied': 'Copied to clipboard',
    'student.catalog.viewMore': 'View course',
    'student.catalog.communityBadge': 'Community',
    'teacher.students.gradingTitle': 'Students & Grading',
    'teacher.students.selectCourse': 'Select Course',
    'teacher.students.table.student': 'Student',
    'teacher.students.table.average': 'Average',
    'teacher.students.noStudents': 'No students enrolled yet',
    'common.xp': 'XP: {xp}',
    'common.streakDays': '{days} day streak',
    'common.level': 'Level {level}',
  },
  kk: {
    'brand.name': 'Cognify',
    'layout.logout': 'Шығу',
    'layout.theme': 'Тақырып',
    'layout.language': 'Тіл',
    'layout.dark': 'Қараңғы',
    'layout.light': 'Жарық',
    'nav.teacher.dashboard': 'Шолу',
    'nav.teacher.courses': 'Курстарым',
    'nav.teacher.create': 'Курс құру',
    'nav.teacher.students': 'Студенттер',
    'nav.student.dashboard': 'Оқуым',
    'nav.student.catalog': 'Каталог',
    'nav.student.admin': 'Талдау',
    'auth.title': 'Cognify',
    'auth.login.subtitle': 'Оқуды жалғастыру үшін кіріңіз',
    'auth.register.subtitle': 'Оқуды бастау үшін тіркеліңіз',
    'auth.login': 'Кіру',
    'auth.register': 'Тіркелу',
    'auth.name': 'Аты-жөні',
    'auth.email': 'Email',
    'auth.password': 'Құпиясөз',
    'auth.student': 'Студент',
    'auth.teacher': 'Оқытушы',
    'teacher.welcome': 'Қайта оралыңыз, {name}',
    'teacher.workspace': 'Сіздің оқыту кеңістігі дайын',
    'teacher.createCourse': 'Курс құру',
    'teacher.totalStudents': 'Барлығы студенттер',
    'teacher.activeCourses': 'Белсенді курстар',
    'teacher.enrollments': 'Тіркелулер',
    'teacher.aiCourses': 'AI курстары',
    'teacher.avgScore': 'Орта балл',
    'teacher.completion': 'Аяқталды',
    'teacher.atRisk': 'Тәуекелді ортада',
    'teacher.weakTopics': 'Сендіпусикон тақырыптар',
    'course.lessons': 'Сабақтар',
    'course.modules': 'Модульдер',
    'course.students': 'Студенттер',
    'course.progress': 'Прогресс',
    'course.start': 'Бастау',
    'course.continue': 'Жалғастыру',
    'teacher.riskGroup': 'Тәуекел тобы (<50)',
    'teacher.needsAttention': 'Назар аудару қажет',
    'teacher.courseHealth': 'Курс сау болуы',
    'teacher.recentCourses': 'Соңғы курстар',
    'teacher.noCourses': 'Әзі курс жоқ.',
    'teacher.viewAllCourses': 'Барлық курстарды қарау',
    'teacher.studentsAtRisk': 'Тәуекелді студенттер',
    'teacher.noRiskStudents': 'Әзі тәуекелді студент жоқ.',
    'teacher.openGrading': 'Бағалауды ашу',
    'teacher.weakTopicsAnalytics': 'Сыбай тақырыптар аналитикасы студенттердің викториналын өндіргеннен кейін пайда болады.',
    'teacher.flags': 'белгілер',
    'teacher.automationSnapshot': 'Автоматика снимокі',
    'teacher.automationDesc': 'AI құрастырушы, тәуекел бағалау, бағалау, бейімтелген тесттер, сертификаттар және дербес студент нұсқау қазір іс жүргіптеді.',
    'teacher.completionRate': 'Аяқталу коэффициенті',
    'teacher.averageScore': 'Орта балл',
    'student.catalog.title': 'Оқу әлемін зерттеңіз',
    'student.catalog.subtitle': 'Сізге арналған жеке AI оқу жолдары.',
    'student.catalog.searchPlaceholder': 'Курстарды іздеу...',
    'student.catalog.trendingTitle': 'Тренд тақырыптар',
    'student.catalog.clearFilter': 'Фильтрді тазалау',
    'student.catalog.resourcesTitle': 'Қатысты ресурстар',
    'student.catalog.resource.precision.title': 'Текті ауыл шаруашылығы негіздері',
    'student.catalog.resource.precision.desc': 'Деректерге негізделген егін шаруашылығы, дақылдарды бақылау және дәл енгізу жоспарлау.',
    'student.catalog.resource.drone.title': 'Ауыл шаруашылығы үшін дрондық карталау',
    'student.catalog.resource.drone.desc': 'Дрондық зерттеулер, маршруткаларды карталау, кескіндерді түсіру және алаңды тексеру процесстері.',
    'student.catalog.resource.soil.title': 'Агрономия және топырақты басқару',
    'student.catalog.resource.soil.desc': 'Топырақ құнарлылығы, суаруды басқару, егін айналымы және тұрақты егістік шешімдер.',
    'student.catalog.noCourses': 'Қазіргі уақытта курс жоқ.',
    'student.catalog.enroll': 'Тіркелу',
    'student.catalog.enrolling': 'Тіркелуде...',
    'student.catalog.enrollSuccess': 'Сіз осы курсқа сәтті тіркелдіңіз.',
    'student.catalog.enrollError': 'Тіркеу сәтсіз аяқталды. Қайта байқап көріңіз.',
    'student.catalog.favoriteAdded': 'Курс фавориттерге қосылды.',
    'student.catalog.favoriteRemoved': 'Курс фавориттерден алынып тасталды.',
    'student.catalog.defaultCourseDescription': 'Бұл таңдаулы оқу бағдарламасына кіріп, Cognify AI-пен жаңа биіктерді меңгеріңіз.',
    'student.catalog.completed': 'Аяқталды',
    'student.catalog.progress': 'Прогресс',
    'student.dashboard.aiTutorStatus': 'ЖИ репетиторы қосулы',
    'teacher.courses.descriptionFallback': 'Студенттер осы курс арқылы не үйренетінін сипаттауға осы орынды пайдаланыңыз.',
    'student.dashboard.heroTitle': 'Қайта оралыңыз, {name}! AI саяхатыңызды жалғастыруға дайынсыз ба?',
    'student.dashboard.heroSubtitle.courses': 'Сізге арналған жеке оқу жолдары дайын. Оқу прогресін жалғастыру үшін курсты таңдаңыз.',
    'student.dashboard.heroSubtitle.empty': 'Сіз әлі ешқандай курсқа тіркелмегенсіз. Оқу каталгін тексеріңіз.',
    'student.dashboard.browseCatalog': 'Каталогты шолу',
    'student.dashboard.portfolioTitle': 'Менің оқу портфелім',
    'student.dashboard.loadingDashboard': 'Панельді жүктеу...',
    'student.dashboard.noCourses': 'Сіз қазіргі уақытта ешқандай курсқа тіркелген жоқсыз.',
    'student.dashboard.recommendationsTitle': 'Келесі әрекеттеріңіз',
    'student.dashboard.recommendedCoursesTitle': 'Ұсынылатын келесі курстар',
    'student.dashboard.recommendationsEmpty': 'Тапсырманың немесе викторинаның біреуін орындау арқылы жеке әрекет жоспары ашылады.',
    'student.dashboard.recommendedCoursesEmpty': 'Жеке ұсыныстар оқу профилі өсірілгеннен кейін пайда болады.',
    'student.dashboard.focusAreasTitle': 'Назар аудару салалары',
    'student.dashboard.focusAreasEmpty': 'Сіздің әлсіз тақырып талдауыңыз викторинадан кейін осында пайда болады.',
    'student.dashboard.resumeLearning': 'Оқуды жалғастыру',
    'teacher.courses.title': 'Менің курстарым',
    'teacher.courses.headerDesc': 'Оқыту портфолиосын басқарыңыз және сенімді түрде курс жасаңыз.',
    'teacher.courses.searchPlaceholder': 'Курс атауын немесе сипаттамасын іздеу...',
    'teacher.courses.filterAll': 'Барлық курстар',
    'teacher.courses.filterAI': 'AI курстар',
    'teacher.courses.filterManual': 'Қолмен жасалған курстар',
    'teacher.courses.noMatches': 'Ағымдағы сүзгілерге сәйкес курс жоқ.',
    'teacher.courses.sharedTitle': 'Қоғамдық курстар',
    'teacher.courses.sharedSubtitle': 'Сіздің жеке оқыту каталогыңыздан тыс жасалған немесе қосылған курстар.',
    'teacher.courses.aiGenerated': 'AI генерацияланған',
    'teacher.courses.manual': 'Қолмен',
    'teacher.courses.students': '{count} студент',
    'teacher.courses.openCourse': 'Курсты ашу',
    'teacher.courses.editCourse': 'Курсты өңдеу',
    'landing.nav.features': 'Мүмкіндіктер',
    'landing.nav.solutions': 'Шешімдер',
    'landing.nav.signin': 'Кіру',
    'landing.hero.badge': '🚀 Жаңа Cognify 2.0: Болашаққа қадам',
    'landing.hero.title': 'Білім берудің<br/>жаңа дәуірі.',
    'landing.hero.subtitle': 'ЖИ-мен бейімделген оқу, RPG режимдері және терең аналитика. Білім берудің болашағына қош келдіңіз.',
    'landing.hero.cta.start': 'Тегін бастау',
    'landing.hero.cta.explore': 'Платформамен танысу',
    'landing.preview.shield': 'ЖИ тексерді',
    'landing.preview.score': 'Балл: 98% 🌟',
    'landing.preview.level': 'Жаңа деңгей!',
    'landing.preview.levelSub': 'Сіз 12 деңгейге жеттіңіз',
    'landing.features.title': 'Заманауи оқушы үшін жасалған',
    'landing.features.subtitle': 'Әлемдік деңгейдегі білім беру тәжірибесін ұсынуға қажеттінің бәрі.',
    'landing.features.ai.title': 'ЖИ көмегімен құру',
    'landing.features.ai.desc': 'Толық курстарды, викториналарды және бейімделу оқу жолдарын секунд ішінде жасаңыз.',
    'landing.features.rpg.title': 'RPG геймификациясы',
    'landing.features.rpg.desc': 'Оқу бағдарламасын 2D картаға айналдырыңыз. Студенттер аралдарды зерттеп, XP жинайды.',
    'landing.features.analytics.title': 'Нақты уақыттағы аналитика',
    'landing.features.analytics.desc': 'Тәуекелді бағалау алгоритмдерімен және PDF есептермен артта қалғандарды лезде табыңыз.',
    'common.loading': 'Жүктеу...',
    'nav.aiLibrary': 'AI Кітапханасы',
    'ai.library.title': 'AI Кітапханасы',
    'ai.library.subtitle': 'Білім беру ресурстары мен ЖИ құралдарын зерттеңіз',
    'ai.library.searchLabel': 'Іздеу сұранысы немесе мәтін',
    'ai.library.searchPlaceholder': 'Тақырыпты, сөзді немесе мәтінді енгізіңіз...',
    'ai.library.mode': 'Режим',
    'ai.library.mode.search': 'Кітапханадан іздеу',
    'ai.library.mode.translate': 'Мәтінді аудару',
    'ai.library.mode.summarize': 'Мәтінді қысқарту',
    'ai.library.targetLang': 'Аударма тілі',
    'ai.library.action.search': 'Іздеу',
    'ai.library.action.processing': 'Өңдеу...',
    'ai.library.results.translation': 'Аударма',
    'ai.library.results.summary': 'Қысқаша мазмұны',
    'ai.library.results.items': 'Кітапхана нысандары',
    'ai.library.results.related': 'Қатысты ресурстар',
    'ai.library.empty': 'Кітапханадан іздеу үшін сұраныс енгізіңіз',
    'ai.library.copy': 'Көшіру',
    'ai.library.copied': 'Алмасу буферіне көшірілді',
    'student.catalog.viewMore': 'Курсты қарау',
    'student.catalog.communityBadge': 'Қоғамдастық',
    'teacher.students.gradingTitle': 'Студенттер және Бағалар',
    'teacher.students.selectCourse': 'Курсты таңдаңыз',
    'teacher.students.table.student': 'Студент',
    'teacher.students.table.average': 'Орта балл',
    'teacher.students.noStudents': 'Студенттер әлі жоқ',
    'common.xp': 'Ұпай: {xp}',
    'common.streakDays': '{days} күндік серия',
    'common.level': '{level} деңгей',
  },
};

interface PreferencesContextValue {
  theme: Theme;
  language: Language;
  setLanguage: (language: Language) => void;
  toggleTheme: () => void;
  t: (key: string, fallback?: string, vars?: Record<string, string | number>) => string;
}

const PreferencesContext = createContext<PreferencesContextValue | undefined>(undefined);

export const PreferencesProvider = ({ children }: { children: ReactNode }) => {
  const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('theme') as Theme) || 'dark');
  const [language, setLanguageState] = useState<Language>(() => (localStorage.getItem('language') as Language) || 'ru');

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem('theme', theme);
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const value = useMemo<PreferencesContextValue>(
    () => ({
      theme,
      language,
      setLanguage: setLanguageState,
      toggleTheme: () => setTheme((prev) => (prev === 'dark' ? 'light' : 'dark')),
      t: (key: string, fallback?: string, vars?: Record<string, string | number>) => {
        let text = DICTIONARY[language][key] || fallback || key;
        if (vars) {
          Object.entries(vars).forEach(([k, v]) => {
            text = text.replace(`{${k}}`, String(v));
          });
        }
        return text;
      },
    }),
    [theme, language],
  );

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
};

export const usePreferences = () => {
  const context = useContext(PreferencesContext);
  if (!context) {
    throw new Error('usePreferences must be used within PreferencesProvider');
  }
  return context;
};
